# Profil par defaut (H2 local)
spring.profiles.default=local

# Serveur
server.port=8080

# JPA (commun)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# JWT
app.jwt.secret=${APP_JWT_SECRET:VGhpc0lzQVNlY3VyZUFuZExvbmdFbm91Z2hCYXNlNjRTZWNyZXRLZXlGb3JKV1Q=}
app.jwt.expiration-ms=86400000

# Securite / bootstrap
app.security.secure-cookie=false
app.seed-demo-data=false
